#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=16GB
#SBATCH --partition=gpu
#SBATCH --gres=gpu:a100:2
#SBATCH --time=1-18:00:00
#SBATCH --account=xiangren_818

module purge

eval "$(conda shell.bash hook)"

conda activate /home1/dpwani/.conda/envs/vqa-2

python -u train_cpgn_length.py --data data/parsed_data.h5 --model length_v3.pt --eval_mode True  --gpu 0
